### ISSUE TITLE
Notification needs more details

### ISSUE THREAD

**Issue by sanctimoniousape** [jd1378/otphelper#88] opened 2024-05-14 13:05 UTC
The in-notification options to ignore app or tag don't specify what app or tag you're about to ignore, making choosing one a pointless exercise in the form of a game of Russian Roulette.

The notification should always specify ***which*** app notification came from, and preferably even copy and display the entire notification text it parsed just so we know where it's coming from.  I leave many notifications active on my phone for later attention, so finding what triggered your app can often be a PITA.

I know it's been mentioned before, but I'm still having issues with this parsing the text message for the code, copying it, then immediately copying the "short code" number that the message came from - thus overwriting the needed code, and making your app practically useless. Older versions worked better in this regard, but I don't recall exactly which version the regression started with

**Comment by jd1378** [comment] 2024-05-14 13:28
Hi 
Regarding the ignore buttons, that's a valid argument and I agree with you, I'll try to improve it in future

Regarding incorrect codes being copied, thats why I add unit tests, to prevent regression
Whenever someone says this code is not detected or x is detected incorrectly, i almost always add a test, unless it's hard to ignore incorrect codes

But I hope to improve the experience by both adding a detection history, and keyword management in future when I get the time

**Comment by jd1378** [comment] 2024-05-14 13:30
Now if you mention what code from what message is being incorrectly copied i will try to fix it if possible

**Comment by sanctimoniousape** [comment] 2024-05-14 13:42
The one that finally drove me to post this today is one that I still have absolutely NO Idea what the source message was - I even checked the recent notification history  It popped up a four-digit code, but I couldn't find any active notification containing it.

If I can come up with a concrete example, I will try to post it.  I only get codes specifically, so it may be a few days.

**Comment by pataquets** [comment] 2024-06-07 11:19
Same here. Sometimes I see some notifications which clearly are not SMS PINs, but I'm afraid to blacklist the entire app, since it's not obvious which one triggered and leaves me guessing.
Just as an idea/suggestion: wouldn't it make it any easier to just add the app name to the "Ignore" button string, so it shows "Ignore 'Gmail'"?

**Comment by jd1378** [comment] 2024-07-09 14:39
I've added the History screen to 1.16.0 (which is released as rc right now)
I have also added a "Show Details" button to the detection notification which will open the corresponding history detail
you can try it now:
https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc

**Closed by jd1378** 2024-07-09 14:39 UTC
