### ISSUE TITLE
The application no longer works when the phone is restarted. V. 1.14.1

### ISSUE THREAD

**Issue by franco27** [jd1378/otphelper#82] opened 2024-05-01 11:01 UTC
Hello,

With version number 1.14.1

Just a few months ago, I installed your application and discovered it. After the installation, I noticed that your application was working perfectly on my mobile phone. On several occasions, thanks to your application, I was able to copy the code. (even after restarting the phone it worked correctly)

Recently, probably due to an update, I realized that your application was no longer working at all. I noticed that there have been several updates since I discovered this issue. However, since I do not regularly receive SMS messages with a code, I do not remember the version I initially installed.

After uninstalling, restarting the phone, and reinstalling your application which did not solve the problem, I am reaching out to you in hopes that you can resolve this issue.

My phone is a Xiaomi brand and of course, I have respected the requirements for the settings. For your application, I have disabled battery optimization, enabled the setting for your application to run in the background, and also in the security settings, I have enabled the lock on the window of your application. I have enabled automatic startup. I have given permission for notification access.

It is on this last setting that I have noticed a problem with your application. Every time I start my mobile phone, I have to re-enable notification access permission (I have to disable and re-enable it again for the application to function properly and this happens every time I start).

Otherwise, upon starting the phone when I test notifications, I only receive one notification from your application. I do not receive the two notifications, one titled "notification test" (this is the only notification I receive) and the other with the code where I can copy "detected code".

My smartphone system configuration
Xiaomi Redmi 8
Android Version 10 Android 10
MIUI V12.5.2.0.QCNEUXM

Architecture 64-bit

Instruction sets
arm64-v8a armeabi-v7a armeabi Qualcomm® Snapdragon™ 439

CPU 4 x Cortex-A53
Cores 8
RAM size 4 GB

![IMG_20240421_070657.jpg](https://github.com/jd1378/otphelper/assets/31793920/b115a1b2-15e3-44d2-80a9-657663cf20a8)

**Comment by jd1378** [comment] 2024-05-01 12:45
Hi
thanks for taking your time to write this
I am aware of the notification permission issue, which is most likely a bug on certain android OS versions, as it does not happen on my phones (which are both Xiaomi and one is android 13, and the other is android 14 on HyperOS). so I don't really know how to solve it, unless there's a fix that I am unaware of

regarding your issue in general, I did not understand, does the app now stop working after a while on it's own, or is this completely about the notification permission?

if the app stops working after a while with the latest updates, I suspect that the issue is the recent change to app's activity props, which I will revert if that's the case

**Comment by franco27** [comment] 2024-05-01 13:10
I am on Android 10 with a Xiaomi phone that has not received major updates in over 2 years. Now I will stick with Android 10. 

Now when I receive updates, they are for system modules that I have not had for several months. 

Does the app stop working? I don't think so because I have checked that. After several hours, I repeated the notification test from your app multiple times with varying durations, such as half a day, a morning, or several hours. And every time I do the notification test, both notifications appear. 

I lose notification access permission every time I restart the phone. As I mentioned, every time I restart the phone, I do the notification test and only receive one out of the two notifications. When I disable and re-enable notification access, I no longer have a problem and the notification test works correctly, with both notifications being received. 

This was not an issue when I initially installed your app several months ago. But I no longer remember which version number I initially installed. I only remember that the app was in French. 

When I reinstalled the current version, there was no update because before it arrived, I had uninstalled a previous version. There have been multiple phone restarts.

**Comment by franco27** [comment] 2024-05-01 13:18
It's been recently or just a few days since I noticed the issue with the notification access parameter. Since then, I have not received any codes via SMS. Therefore, in theory, if I receive both notifications, it should work correctly if I receive a code via SMS. I searched online for a service that could send a test with a code via SMS, but I did not find one.

**Comment by jd1378** [comment] 2024-05-01 13:26
I see

the notification access permission did exists even before the app was released, when I was still testing the app on my family members' phones, so I am sure of this fact

what I have doubts now, is that maybe somehow at some point it got fixed accidently without me knowing for people like you, which makes it extremely difficult to find the cause

however I understand your frustration, I try to look into it when I have some time, maybe I find some solution, but I wouldn't get my hopes up

**Comment by franco27** [comment] 2024-05-01 13:33
Thank you for your response and I hope you will find where the problem lies.

I wish you a happy May 1st.

**Comment by jd1378** [comment] 2024-05-12 02:28
I tried looking up the issue and could not find a single thing on this, as not many developers are interested in reading all notifications

however I added a check on app's auto start on reboot which hopefully should show a notification when the permission has been revoked, which when tapped will open the settings for granting the permission again

this was the best I could do to at least make it more convenient

it will be released soon as 1.15.0

**Comment by jd1378** [comment] 2024-05-12 15:09
I added a fix in 1.15.1 which may fix the auto start issue without the need to re-granting the permission
please try it out and let me know how it works for you @franco27

**Comment by franco27** [comment] 2024-05-14 20:33
Thank you for trying to fix the issue. Unfortunately, the malfunction still persists. 

In version 1.15.0, I am not being notified when the notification test does not work. In version 1.15.1, I still have to disable and re-enable notification access every time I start my mobile phone. 

I will try to uninstall, restart the mobile phone, and reinstall your application with version 1.15.1. Maybe this time it will work.

**Comment by jd1378** [comment] 2024-05-14 20:44
Hi
then I think the fix is useless, cause another person had exactly the same issue and it did not resolve it for him as well
I simply have to post the notification on every reboot on android 10 and 11, regardless of the permission status

**Comment by franco27** [comment] 2024-05-23 17:24
Upon restarting the mobile phone, there is now a notification to remind you to reactivate the notification access permission 🔔

In the latest version, this works correctly and thank you for adding it. It's very useful, and thank you.

**Comment by franco27** [comment] 2024-07-10 13:34
Hello,
Yesterday I updated to version v1.16.0-rc.

I noticed an issue with notifications after restarting my mobile phone.
With the previous version, when I clicked on the notification, the settings window to re-enable notification access permission would appear directly.
With this version, it no longer appears. I mean, when there is a notification, it only opens your application.

However, I had a very pleasant surprise because apparently notification access was still correctly enabled after restarting the mobile phone.
Usually, after every restart of the mobile phone, I had to click on the notification to access the settings and re-enable notification access.

I did not receive any SMS to test if your application was working correctly, but it did work correctly with the test button. I received both notifications.

For Xiaomi and Android 10.

**Comment by franco27** [comment] 2024-07-11 19:17
False hope 🤔
I restarted my mobile phone this morning.
Yesterday was the first restart of the mobile phone after installing the update.
The same problem has reappeared and this time when I clicked on the notification, I was taken directly to the Android settings to reactivate notification access.

I don't understand.

**Comment by jd1378** [comment] 2024-07-11 19:40
hmm
that's sad,  I wish it was fixed
anyway, I think I know the issue with the notification working and not working sometimes, will include a fix for the next version

**Comment by jd1378** [comment] 2024-07-12 13:51
Can you try installing https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc4 and see if it has fixed your issue?
this one contains another fix that I really really hope it fixes your issue

also try to follow this guide for allowing the app to auto start, if the auto start permission from "Permissions" settings is not helping:
https://dontkillmyapp.com/xiaomi

please let me know how it goes for you

**Comment by franco27** [comment] 2024-07-14 11:59
T

**Comment by jd1378** [comment] 2024-07-14 13:20
well if It's fixed, the notification will be a nuisance 

since you were receiving the notification, and the permission was granted and you were just disabling and enabling it again, I conclude that the app was being launched at startup, it was just not registering the listener service properly

now that the app **_does_** register the listener service properly, the notification is no longer needed

thanks a lot for testing and reporting the results so far :)

**Closed by jd1378** 2024-07-14 13:20 UTC
