### ISSUE TITLE
It is recommended to add a switch to hide background processes

### ISSUE THREAD

**Issue by xxxxxxxxxxx-o** [jd1378/otphelper#71] opened 2024-04-03 06:35 UTC
Hiding background processes will make the software more seamless to use. Many apps support hiding background processes. I hope this feature can be added. Thank you. The software is very easy to use, and it is like a native system!

**Comment by jd1378** [comment] 2024-04-03 12:04
Hi
I'm sorry but I did not understand what feature you are referring to
maybe a link or screenshot so I can understand better ?
thanks

**Comment by Boomz123** [comment] 2024-04-14 11:18
What he means is to hide the background display in multitasking.

**Comment by Boomz123** [comment] 2024-04-14 11:24
![Screenshot_20240414_192311_com huawei android launcher](https://github.com/jd1378/otphelper/assets/166996243/a27d6353-38fd-4b7b-b561-4f7a70a4489b)

**Comment by Boomz123** [comment] 2024-04-14 11:33
> Hi I'm sorry but I did not understand what feature you are referring to maybe a link or screenshot so I can understand better ? thanks

What he means is to hide the background display in multitasking.

**Comment by jd1378** [comment] 2024-04-14 12:08
Is there another app that has this feature that i can look at its source code?
I'm still not sure if I understood correctly

**Comment by Boomz123** [comment] 2024-04-14 12:25
> Is there another app that has this feature that i can look at its source code? I'm still not sure if I understood correctly

The Android system will display all running programs when retrieving multitasking, and the owner wants to hide it so that the multitasking manager is not detected when the host pulls it up.

**Comment by Boomz123** [comment] 2024-04-14 12:33
Do not display background applications

**Comment by jd1378** [comment] 2024-04-14 13:32
I think i finally understood what you mean

Well I don't understand why it is needed in the first place
The app simply remains open in the background, even if you close it from the screenshot you have posted

It remaining there until swiped away is better ux, and it does not affect functionality of the app

**Comment by jd1378** [comment] 2024-04-14 13:34
You don't need to lock it in order to keep it open

**Comment by Boomz123** [comment] 2024-04-14 14:34
> I think i finally understood what you mean我想我终于明白你的意思了
> 
> Well I don't understand why it is needed in the first place好吧，我不明白为什么首先需要它 The app simply remains open in the background, even if you close it from the screenshot you have posted该应用程序只是在后台保持打开状态，即使您从发布的屏幕截图中将其关闭
> 
> It remaining there until swiped away is better ux, and it does not affect functionality of the app它一直留在那里直到滑动是更好的用户体验，并且不会影响应用程序的功能

Because on Huawei phones, once you clear it from the background, it will become invalid.

**Comment by Boomz123** [comment] 2024-04-14 14:40
It is common to accidentally operate due to closing other applications, and adding a switch to hide background display in software would be a good choice.

**Comment by jd1378** [comment] 2024-04-14 15:13
Oh, i see ...
Well maybe its for the best to hide it for everyone by default if it improves usability

**Comment by Boomz123** [comment] 2024-04-18 12:01
> released in [1.14.1](https://github.com/jd1378/otphelper/releases/tag/v1.14.1)

There is a similar app called SmsCodeHelper, which has a smaller size, faster response, and lower power consumption. You can learn from it. However, I really like your app because the copied verification code does not directly display numbers, which is more private.

**Comment by Boomz123** [comment] 2024-04-20 11:49
It is recommended to change the automatic hiding of the background display to automatic hiding when the program exits normally, otherwise it will continue to be displayed in the background. This can avoid killing the backend due to misoperation.

**Comment by jd1378** [comment] 2024-04-20 14:13
Hi
What do you mean ?
Is the current behavior not what you meant ? 
How is it causing problem?

**Comment by Boomz123** [comment] 2024-04-21 00:04
> Hi What do you mean ?你是什么意思？ Is the current behavior not what you meant ?当前的行为不是您的意思吗？ How is it causing problem?它是如何引起问题的？

Huawei phones can kill the backend and must be manually locked in a multitasking interface to avoid failure. You can study and take a look at another software on the platform called "SmsCodeHelper" for its hiding method.

**Comment by jd1378** [comment] 2024-05-12 02:35
I checked the application you mentioned and it uses the same 
[excludeFromRecents](https://github.com/RikkaW/SmsCodeHelper/blob/d8eb66153074df0e2a62938c1ce268a7cb0a9899/app/src/main/AndroidManifest.xml#L17) attribute

the problem is mostly because of buggy behavior of android for reading notifications
if the app changes behavior to reading SMS instead of notification, I think the issue will be solved

I have made another issue for it, I try to implement it when I have time:
https://github.com/jd1378/otphelper/issues/86

**Closed by jd1378** 2024-05-12 02:35 UTC
